name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_macos:
    env:
      CODECOV_TOKEN : 274bae88-45e7-4836-a5f4-3b8c7e3efdf8
    
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: xcodebuild -scheme KeyValueCache test -destination 'platform=macOS' -enableCodeCoverage YES -parallel-testing-enabled YES build test

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -X xcodellvm

  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      
    - name: Run tests
      run: swift test 
